### ISSUE TITLE
Data Migration?

### ISSUE THREAD

**Issue by kbuika** [Code-Matata/tusomeni-backend-app#1]
Hey @Asahel-code, 

I have just seen this repo right now, nice setup. We had ultimately agreed to rebuild the backend with Nodejs and move the database from Postgres to MongoDB. But what is the strategy with data migration or will we have to republish all the documents onto MongoDB?

Also, if you may, could you please add all the tasks to be completed as tasks - basically, we are rebuilding the current API from  Java(SpringBoot) to NodeJS, and it would be helpful to have all the tasks added as issues or under Projects so that we know who is working on what.

cc: @willynganga @abdiomari

**Comment by Asahel-code** [comment]
Hi @kibuikaCodes.
I have seen they have a lot of issues about the current running app, i would like to add another one. Do we still have data for the postgres database?
cc: @willynganga @abdiomari

**Comment by kbuika** [comment]
It is a hosted postgres DB. I am not sure about that. @willynganga how easy would it be to export the data from postgres?

**Comment by willynganga** [comment]
Unfortunately we don't have the data, it was destroyed by Heroku.

**Comment by kbuika** [comment]
Okay, I'll have to dig into my archives and find all the files we had and reupload them into the new Database
